import { createContext, useContext, type ReactNode } from "react";

import type { Locale } from "../hooks/useAppSettings";

const copy = {
  en: {
    agents: "Agents", sessions: "Sessions", documents: "Documents", tools: "Tool registry", settings: "Settings", openSidebar: "Open sidebar", closeSidebar: "Close sidebar",
    workspace: "Workspace", newAgent: "New agent", newSession: "New session", searchAgents: "Search agents",
    searchSessions: "Search sessions", searchDocuments: "Search documents", signOut: "Sign out", complete: "complete",
    copy: "Copy", copied: "Copied", toolsUsed: "Tools", retrieved: "Retrieved", none: "None",
    startConversation: "Start a conversation with {agent}", attachDocument: "Attach a document for this answer or add one to the shared library in the inspector.",
    settingsTitle: "Settings", settingsSummary: "Personalize this browser’s AI Platform experience.",
    appearance: "Appearance", workspaceSettings: "Workspace", privacy: "Privacy & data", notifications: "Notifications", legal: "Legal", legalDescription: "Review the policies that govern your use of AI Platform.", terms: "Terms", privacyPolicy: "Privacy", cookies: "Cookies",
    theme: "Theme", language: "Language", dark: "Dark", light: "Light", system: "System", english: "English", hebrew: "עברית",
    apiConnected: "API connected", apiUnavailable: "API unavailable", messages: "messages", now: "now", delete: "Delete", deleteSession: "Delete session",
    configuration: "Configuration", traces: "Traces", currentSession: "Current session", noTraces: "No traces yet", traceHint: "Tool calls and retrieval activity appear here after an agent responds.", assistantTurn: "Assistant turn {number}", chunks: "chunks", chunk: "chunk",
    appearanceDescription: "Choose how AI Platform looks on this device.", compactLayout: "Compact layout", compactLayoutDetail: "Reduce spacing across the workspace.", reduceMotion: "Reduce motion", reduceMotionDetail: "Limit decorative animations.", highContrast: "High contrast", highContrastDetail: "Strengthen text and interface boundaries for easier reading.",
    workspaceDescription: "Language and reading direction for this browser.", hebrewHint: "Hebrew enables right-to-left layout. Workspace content and model output remain unchanged.", privacyDescription: "Control what this browser keeps and displays.", showSources: "Show sources", showSourcesDetail: "Display retrieved document citations in answers.", showToolActivity: "Show tool activity", showToolActivityDetail: "Display executed tools and retrieval details.", resetSettings: "Reset settings", resetSettingsConfirm: "Reset AI Platform settings on this browser?",
    chatPreferences: "Chat behavior", chatPreferencesDescription: "Choose how messages are sent and played back.", sendOnEnter: "Send with Enter", sendOnEnterDetail: "Use Shift+Enter for a new line when enabled.", speechInputLanguage: "Speech input language", speechInputAuto: "Match interface", speechInputLanguageHint: "Choose Hebrew to dictate in Hebrew even while using an English interface.", autoReadResponses: "Read responses aloud", autoReadResponsesDetail: "Automatically read completed assistant replies in their detected language.", englishVoice: "English voice", hebrewVoice: "Hebrew voice", preferredVoice: "Recommended system voice", voiceSelectionHint: "Available voices come from this browser and device.", noLocalVoices: "No local voices are available yet. The browser will use its default voice.", testVoice: "Test voice", stopVoicePreview: "Stop voice preview", voicePreviewEnglish: "Hello. This is a preview of the selected voice.", voicePreviewHebrew: "שלום. זוהי דוגמה לקול שנבחר.", navigation: "Navigation", navigationDescription: "Choose how the workspace opens.", sidebarDefaultOpen: "Open sidebar by default", sidebarDefaultOpenDetail: "Show the agent and session drawer when opening a workspace.",
    notificationsDescription: "Choose which in-app status updates appear.", documentIndexing: "Document indexing", documentIndexingDetail: "Notify when a document is ready to use.", toolFailures: "Tool failures", toolFailuresDetail: "Show errors when an enabled tool cannot complete.", longRunningTasks: "Long-running tasks", longRunningTasksDetail: "Notify when a streamed task finishes.",
    workspaceLibrary: "Workspace document library", loadingLibrary: "Loading the shared library…", workspaceDocumentsHint: "Every agent in this workspace can retrieve these documents.", uploadDocument: "Upload document", indexing: "Indexing…", indexed: "Indexed", failed: "Failed", sharedWithAgents: "Shared with every agent in this workspace", deleteDocument: "Delete {name}", deleteDocumentConfirm: "Delete \"{name}\" from the shared document library?", deleting: "Deleting…", noMatchingDocuments: "No matching documents", buildKnowledgeLibrary: "Build a shared knowledge library", tryDifferentFilename: "Try a different filename.", uploadDocumentHint: "Upload a TXT, PDF, or DOCX file. Every agent in this workspace can retrieve it.",
    newAgentTitle: "Give your agent a role.", close: "Close", name: "Name", namePlaceholder: "e.g. Research Scout", shortDescription: "Short description", descriptionPlaceholder: "What this agent is responsible for", model: "Model", temperature: "Temperature", loading: "Loading…", noChatModels: "No chat models installed", installChatModel: "Install a chat-capable model before creating an agent.", systemPrompt: "System prompt", creating: "Creating…", createAgent: "Create agent", saveConfiguration: "Save configuration", configurationSaved: "Configuration saved", saving: "Saving…", unsaved: "Unsaved", saved: "Saved", appliesNextMessage: "Applies to next message", noProviderModels: "No chat-capable models are installed for this provider.", allowedTools: "Allowed tools", selectTool: "Select at least one tool. The backend currently treats an empty list as allow all.", deleteAgent: "Delete agent",
    startHere: "Start here", firstAgentTitle: "Build your first focused agent", firstAgentHint: "Give it a role, add the documents it should know, then enable only the tools it needs.", addDocuments: "Add documents", enableTools: "Enable tools", draft: "draft", noSystemPrompt: "No system prompt yet.", finishSetup: "Finish setup", all: "All", toolsCount: "{count} tools", orTemplate: "or start from a template", dismiss: "Dismiss",
    toolRegistry: "Tool registry", searchTools: "Search tools", registeredTools: "Registered tools", available: "Available", inputSchema: "Input schema", noToolArguments: "This tool does not declare any input arguments.", rawJsonSchema: "Raw JSON schema", noMatchingTools: "No matching tools", noTools: "No tools registered", toolsHint: "Tools appear here when the backend registers them.",
    export: "Export", new: "new", retrievedContext: "Retrieved context", thinking: "Thinking", copyMessage: "Copy message", streaming: "streaming", tokenShort: "tok", stop: "stop", stopGeneration: "Stop generating", moreMessageActions: "More message actions", attachFiles: "Attach file", startVoiceInput: "Start voice input", stopVoiceInput: "Stop voice input", voiceUnsupported: "Voice input is not supported by this browser", readAloud: "Read aloud", stopReading: "Stop reading", textToSpeechUnsupported: "Text-to-speech is not supported by this browser", messageAgent: "Message {agent}", sendMessage: "Send message", newline: "newline", switchAgent: "switch agent", upload: "upload",
    loadingSessions: "Loading retained conversations…", agentForSession: "Agent for new session", noAgents: "No agents", session: "session", sessionCount: "{sessions} sessions across {agents} agents", deleteSessionConfirm: "Delete \"{name}\" and its retained history?", noMatchingSessions: "No matching sessions", noSessions: "No sessions yet", tryDifferentSession: "Try a different session or agent name.", sessionHint: "Start a conversation with an agent and it will appear here.", startSession: "Start a session", message: "message", agoMinutes: "{count}m ago", agoHours: "{count}h ago",
    pdfDocument: "PDF document", markdownFile: "Markdown file", downloading: "Downloading…", retry: "Retry", download: "Download", copyCode: "Copy code to clipboard", copyFailed: "Copy failed",
    chooseAvatar: "Choose avatar", avatarAnimal: "Choose {animal} avatar",
    noMatchingAgents: "No agents match \"{query}\".", toolsSummary: "{count} tools available to agent configurations", argument: "argument", arguments: "arguments", required: "required", optional: "optional", tryToolSearch: "Try a tool name or capability.",
    connectingWorkspace: "Connecting to your workspace…", privateWorkspace: "Private AI workspace", authHeadline: "Turn your documents into work your agents can use.", authDescription: "Create focused agents, attach knowledge, and keep every conversation in one secure workspace.", groundedDocuments: "Grounded in your documents", toolsPerAgent: "Tools you choose per agent", privateAccess: "Private, owner-scoped access", signInPlatform: "Sign in to AI Platform", welcome: "Welcome", continueWorkspace: "Continue to your workspace", signInDescription: "Sign in to access your agents, documents, tools, and retained sessions.", signInFailed: "Sign-in failed or was cancelled. Please try again.", signIn: "Sign in", createAccount: "Create account", authSecured: "Authentication is secured by WorkOS AuthKit.",
  },
  he: {
    agents: "סוכנים", sessions: "שיחות", documents: "מסמכים", tools: "כלי עבודה", settings: "הגדרות", openSidebar: "פתיחת סרגל הצד", closeSidebar: "סגירת סרגל הצד",
    workspace: "סביבת עבודה", newAgent: "סוכן חדש", newSession: "שיחה חדשה", searchAgents: "חיפוש סוכנים",
    searchSessions: "חיפוש שיחות", searchDocuments: "חיפוש מסמכים", signOut: "התנתקות", complete: "הושלם",
    copy: "העתקה", copied: "הועתק", toolsUsed: "כלים", retrieved: "נשלף", none: "ללא",
    startConversation: "התחלת שיחה עם {agent}", attachDocument: "אפשר לצרף מסמך לתשובה זו או להוסיף אותו לספריית המסמכים.",
    settingsTitle: "הגדרות", settingsSummary: "התאמת חוויית AI Platform בדפדפן זה.",
    appearance: "מראה", workspaceSettings: "סביבת עבודה", privacy: "פרטיות ונתונים", notifications: "התראות", legal: "משפטי", legalDescription: "עיון במדיניות החלה על השימוש ב-AI Platform.", terms: "תנאי שימוש", privacyPolicy: "מדיניות פרטיות", cookies: "עוגיות",
    theme: "ערכת נושא", language: "שפה", dark: "כהה", light: "בהיר", system: "מערכת", english: "English", hebrew: "עברית",
    apiConnected: "ה-API מחובר", apiUnavailable: "ה-API אינו זמין", messages: "הודעות", now: "עכשיו", delete: "מחיקה", deleteSession: "מחיקת שיחה",
    configuration: "הגדרה", traces: "מעקב", currentSession: "השיחה הנוכחית", noTraces: "אין מעקבים עדיין", traceHint: "קריאות כלים ופעילות אחזור יופיעו כאן לאחר שהסוכן יגיב.", assistantTurn: "תור סוכן {number}", chunks: "מקטעים", chunk: "מקטע",
    appearanceDescription: "בחרו כיצד AI Platform יוצג במכשיר זה.", compactLayout: "תצוגה צפופה", compactLayoutDetail: "הפחתת המרווחים ברחבי סביבת העבודה.", reduceMotion: "הפחתת תנועה", reduceMotionDetail: "הגבלת הנפשות דקורטיביות.", highContrast: "ניגודיות גבוהה", highContrastDetail: "חיזוק הטקסט וגבולות הממשק לקריאה נוחה יותר.",
    workspaceDescription: "שפת הממשק וכיוון הקריאה בדפדפן זה.", hebrewHint: "עברית מפעילה פריסה מימין לשמאל. תוכן סביבת העבודה ופלט המודל אינם משתנים.", privacyDescription: "שליטה במה שהדפדפן שומר ומציג.", showSources: "הצגת מקורות", showSourcesDetail: "הצגת הפניות למסמכים שנשלפו בתשובות.", showToolActivity: "הצגת פעילות כלים", showToolActivityDetail: "הצגת הכלים שהופעלו ופרטי האחזור.", resetSettings: "איפוס הגדרות", resetSettingsConfirm: "לאפס את הגדרות AI Platform בדפדפן זה?",
    chatPreferences: "התנהגות השיחה", chatPreferencesDescription: "בחירת אופן השליחה וההקראה של הודעות.", sendOnEnter: "שליחה בלחיצה על Enter", sendOnEnterDetail: "כאשר האפשרות פעילה, Shift+Enter יוסיף שורה חדשה.", speechInputLanguage: "שפת הכתבה קולית", speechInputAuto: "לפי שפת הממשק", speechInputLanguageHint: "בחרו עברית כדי להכתיב בעברית גם כאשר הממשק באנגלית.", autoReadResponses: "הקראת תשובות", autoReadResponsesDetail: "הקראה אוטומטית של תשובות סוכן שהושלמו בשפה שזוהתה.", englishVoice: "קול באנגלית", hebrewVoice: "קול בעברית", preferredVoice: "קול המערכת המומלץ", voiceSelectionHint: "הקולות הזמינים מגיעים מהדפדפן והמכשיר הזה.", noLocalVoices: "עדיין אין קולות מקומיים זמינים. הדפדפן ישתמש בקול ברירת המחדל שלו.", testVoice: "בדיקת קול", stopVoicePreview: "עצירת תצוגה מקדימה של הקול", voicePreviewEnglish: "Hello. This is a preview of the selected voice.", voicePreviewHebrew: "שלום. זוהי דוגמה לקול שנבחר.", navigation: "ניווט", navigationDescription: "בחירת אופן פתיחת סביבת העבודה.", sidebarDefaultOpen: "פתיחת סרגל הצד כברירת מחדל", sidebarDefaultOpenDetail: "הצגת מגירת הסוכנים והשיחות בפתיחת סביבת עבודה.",
    notificationsDescription: "בחרו אילו עדכוני מצב יופיעו באפליקציה.", documentIndexing: "אינדוקס מסמכים", documentIndexingDetail: "התרעה כאשר מסמך מוכן לשימוש.", toolFailures: "כשלים בכלים", toolFailuresDetail: "הצגת שגיאות כאשר כלי מורשה לא השלים פעולה.", longRunningTasks: "משימות ארוכות", longRunningTasksDetail: "התרעה כאשר משימה מוזרמת מסתיימת.",
    workspaceLibrary: "ספריית המסמכים של סביבת העבודה", loadingLibrary: "טוען את הספרייה המשותפת…", workspaceDocumentsHint: "כל סוכן בסביבת עבודה זו יכול לאחזר מסמכים אלה.", uploadDocument: "העלאת מסמך", indexing: "מאנדקס…", indexed: "אונדקס", failed: "נכשל", sharedWithAgents: "משותף עם כל סוכן בסביבת עבודה זו", deleteDocument: "מחיקת {name}", deleteDocumentConfirm: "למחוק את \"{name}\" מספריית המסמכים המשותפת?", deleting: "מוחק…", noMatchingDocuments: "לא נמצאו מסמכים תואמים", buildKnowledgeLibrary: "בניית ספריית ידע משותפת", tryDifferentFilename: "נסו שם קובץ אחר.", uploadDocumentHint: "העלו קובץ TXT, PDF או DOCX. כל סוכן בסביבת העבודה יכול לאחזר אותו.",
    newAgentTitle: "העניקו לסוכן תפקיד.", close: "סגירה", name: "שם", namePlaceholder: "למשל: חוקר מידע", shortDescription: "תיאור קצר", descriptionPlaceholder: "על מה הסוכן אחראי", model: "מודל", temperature: "טמפרטורה", loading: "טוען…", noChatModels: "לא מותקנים מודלי שיחה", installChatModel: "יש להתקין מודל שיחה לפני יצירת סוכן.", systemPrompt: "הנחיית מערכת", creating: "יוצר…", createAgent: "יצירת סוכן", saveConfiguration: "שמירת ההגדרה", configurationSaved: "ההגדרה נשמרה", saving: "שומר…", unsaved: "לא נשמר", saved: "נשמר", appliesNextMessage: "חל על ההודעה הבאה", noProviderModels: "לא מותקנים מודלי שיחה לספק זה.", allowedTools: "כלים מורשים", selectTool: "בחרו לפחות כלי אחד. השרת מתייחס כרגע לרשימה ריקה כאל אפשר את כולם.", deleteAgent: "מחיקת סוכן",
    startHere: "התחילו כאן", firstAgentTitle: "בנו את הסוכן הממוקד הראשון שלכם", firstAgentHint: "העניקו לו תפקיד, הוסיפו את המסמכים שעליו להכיר, והפעילו רק את הכלים הנחוצים לו.", addDocuments: "הוספת מסמכים", enableTools: "הפעלת כלים", draft: "טיוטה", noSystemPrompt: "אין הנחיית מערכת עדיין.", finishSetup: "השלמת הגדרה", all: "הכול", toolsCount: "{count} כלים", orTemplate: "או התחילו מתבנית", dismiss: "סגירה",
    toolRegistry: "מאגר כלים", searchTools: "חיפוש כלים", registeredTools: "כלים רשומים", available: "זמין", inputSchema: "סכמת קלט", noToolArguments: "כלי זה אינו מגדיר ארגומנטים לקלט.", rawJsonSchema: "סכמת JSON גולמית", noMatchingTools: "לא נמצאו כלים תואמים", noTools: "לא נרשמו כלים", toolsHint: "כלים יופיעו כאן כאשר השרת ירשום אותם.",
    export: "ייצוא", new: "חדש", retrievedContext: "הקשר שנשלף", thinking: "חושב", copyMessage: "העתקת הודעה", streaming: "מוזרם", tokenShort: "טוקנים", stop: "עצירה", stopGeneration: "עצירת יצירת התשובה", moreMessageActions: "פעולות הודעה נוספות", attachFiles: "צירוף קבצים", startVoiceInput: "התחלת הכתבה קולית", stopVoiceInput: "עצירת הכתבה קולית", voiceUnsupported: "הכתבה קולית אינה נתמכת בדפדפן זה", readAloud: "הקראה", stopReading: "עצירת הקראה", textToSpeechUnsupported: "הקראת טקסט אינה נתמכת בדפדפן זה", messageAgent: "הודעה ל-{agent}", sendMessage: "שליחת הודעה", newline: "שורה חדשה", switchAgent: "החלפת סוכן", upload: "העלאה",
    loadingSessions: "טוען שיחות שמורות…", agentForSession: "סוכן לשיחה חדשה", noAgents: "אין סוכנים", session: "שיחה", sessionCount: "{sessions} שיחות אצל {agents} סוכנים", deleteSessionConfirm: "למחוק את \"{name}\" ואת ההיסטוריה השמורה שלה?", noMatchingSessions: "לא נמצאו שיחות תואמות", noSessions: "אין שיחות עדיין", tryDifferentSession: "נסו שם שיחה או סוכן אחר.", sessionHint: "התחילו שיחה עם סוכן והיא תופיע כאן.", startSession: "התחלת שיחה", message: "הודעה", agoMinutes: "לפני {count} דק׳", agoHours: "לפני {count} שע׳",
    pdfDocument: "מסמך PDF", markdownFile: "קובץ Markdown", downloading: "מוריד…", retry: "ניסיון חוזר", download: "הורדה", copyCode: "העתקת קוד ללוח", copyFailed: "ההעתקה נכשלה",
    chooseAvatar: "בחירת תמונת פרופיל", avatarAnimal: "בחירת תמונת פרופיל של {animal}",
    noMatchingAgents: "לא נמצאו סוכנים התואמים ל-\"{query}\".", toolsSummary: "{count} כלים זמינים להגדרות סוכן", argument: "ארגומנט", arguments: "ארגומנטים", required: "חובה", optional: "אופציונלי", tryToolSearch: "נסו שם כלי או יכולת.",
    connectingWorkspace: "מתחבר לסביבת העבודה…", privateWorkspace: "סביבת עבודה פרטית ל-AI", authHeadline: "הפכו את המסמכים שלכם לעבודה שהסוכנים יכולים להשתמש בה.", authDescription: "צרו סוכנים ממוקדים, צרפו ידע ושמרו כל שיחה בסביבת עבודה מאובטחת אחת.", groundedDocuments: "מבוסס על המסמכים שלכם", toolsPerAgent: "כלים לבחירתכם עבור כל סוכן", privateAccess: "גישה פרטית ומוגבלת לבעלים", signInPlatform: "כניסה ל-AI Platform", welcome: "ברוכים הבאים", continueWorkspace: "המשיכו לסביבת העבודה", signInDescription: "התחברו כדי לגשת לסוכנים, למסמכים, לכלים ולשיחות השמורות שלכם.", signInFailed: "ההתחברות נכשלה או בוטלה. נסו שוב.", signIn: "כניסה", createAccount: "יצירת חשבון", authSecured: "האימות מאובטח באמצעות WorkOS AuthKit.",
  },
} as const;

type Key = keyof typeof copy.en;
type I18n = { locale: Locale; t: (key: Key, values?: Record<string, string>) => string };
const Context = createContext<I18n>({ locale: "en", t: (key) => copy.en[key] });

export function I18nProvider({ locale, children }: { locale: Locale; children: ReactNode }) {
  const t = (key: Key, values: Record<string, string> = {}) => Object.entries(values).reduce(
    (value, [name, replacement]) => value.replace(`{${name}}`, replacement), String(copy[locale][key]),
  );
  return <Context.Provider value={{ locale, t }}>{children}</Context.Provider>;
}

export function useI18n() { return useContext(Context); }
